fix: fix check_miigration

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -93,9 +93,16 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-    - name: Check for new migrations
+    - name: Check migrations
+      env:
+        DATABASE_URL: "sqlite:///:memory:"
+        DJANGO_SETTINGS_MODULE: "task_manager.settings"
+        DEBUG: "0"
+        REDIS_URL: "redis://dummy@localhost:6379/0"
+        EMAIL_HOST: "localhost"
       run: |
-        python manage.py makemigrations --dry-run --check || (echo "Error: New migrations detected. Please run 'makemigrations' and commit them." && exit 1)
-    - name: Check migration conflicts
-      run: |
-        python manage.py makemigrations --check --dry-run || (echo "Error: Migration conflicts detected. Please resolve them." && exit 1)
+        python manage.py makemigrations --dry-run --check || \
+          (echo "::error::New migrations detected. Run 'makemigrations' and commit."; exit 1)
+
+        python manage.py migrate --plan > /dev/null || \
+          (echo "::error::Migration conflicts detected. Resolve them before proceeding."; exit 1)
